### ISSUE TITLE
CSS Modules don't work with SSR

### ISSUE THREAD

**Issue by bartaz** [canonical-ols/javan-rhino#20]
Using CSS modules:

```js
import React, { Component } from 'react';
import NavLink from '../components/navlink';

import styles from './header.css';

export default class Header extends Component {
  render() {
    return <div className={ styles.header }>
      <NavLink to="/" onlyActiveOnIndex={ true }>Home</NavLink>
      <NavLink to="/about">About</NavLink>
    </div>;
  }
}
```

Causes webpack/babel error on `npm start`:

```
SyntaxError: /Users/bartaz/Canonical/javan-rhino/src/components/header.css: Unexpected token (1:0)
> 1 | .header {
    | ^
  2 |   background: red;
  3 | }
  4 | 
    at Parser.pp.raise (/Users/bartaz/Canonical/javan-rhino/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/bartaz/Canonical/javan-rhino/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseExprAtom (/Users/bartaz/Canonical/javan-rhino/node_modules/babylon/lib/parser/expression.js:522:12)
    at Parser.parseExprAtom (/Users/bartaz/Canonical/javan-rhino/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
    at Parser.pp.parseExprSubscripts (/Users/bartaz/Canonical/javan-rhino/node_modules/babylon/lib/parser/expression.js:277:19)
    at Parser.pp.parseMaybeUnary (/Users/bartaz/Canonical/javan-rhino/node_modules/babylon/lib/parser/expression.js:257:19)
    at Parser.pp.parseExprOps (/Users/bartaz/Canonical/javan-rhino/node_modules/babylon/lib/parser/expression.js:188:19)
    at Parser.pp.parseMaybeConditional (/Users/bartaz/Canonical/javan-rhino/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/bartaz/Canonical/javan-rhino/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.parseMaybeAssign (/Users/bartaz/Canonical/javan-rhino/node_modules/babylon/lib/plugins/flow.js:460:20)
```

**Comment by bartaz** [comment]
Fixed by #22
